[versions]
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.6.2"
activityCompose = "1.8.2"
composeBom = "2024.01.00"
androidxTestExtJUnit = "1.1.5"
espressoCore = "3.5.1"
junit = "4.13.2"
hiltAndroid = "2.48"
hiltCompiler = "2.48"
roomRuntime = "2.6.1"
roomKtx = "2.6.1"
roomCompiler = "2.6.1"
androidGradlePlugin = "8.2.0"
kotlinGradlePlugin = "1.9.22"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJUnit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltCompiler" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinGradlePlugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

[bundles]
compose = ["ui", "ui-graphics", "ui-tooling-preview", "material3"]
room = ["room-runtime", "room-ktx", "room-compiler"]
hilt = ["hilt-android", "hilt-compiler"]